FROM ubuntu:24.04

RUN mkdir -p /qt/installed
WORKDIR /qt

RUN apt-get update
RUN apt-get install -y build-essential libgl1-mesa-dev wget cmake libxcb-icccm4 libxcb-image0  libxcb-keysyms1 libxcb-render-util0 libxcb-shape0 libxcb-xinerama0 \
    libxcb-xkb1 libxkbcommon-x11-0 libdbus-1-3
RUN apt-get install -y qt6-base-dev-tools

COPY qt-unified-linux-x64-4.6.1-online.run qt.run

RUN chmod 755 qt.run
RUN --mount=type=secret,id=email,env=QT_EMAIL \
    --mount=type=secret,id=password,env=QT_PASSWORD \
    ./qt.run --root /qt/installed --accept-licenses --accept-obligations --accept-messages --confirm-command \
    --email "${QT_EMAIL}" --pw "${QT_PASSWORD}" install "qt.qt6.652.gcc_64" "qt.qt6.652.addons.qtwebsockets" "qt.tools.cmake" "qt.tools.opensslv3"

RUN rm qt.run
